nelmio_api_doc:
    documentation:
        info:
            title: Library Management System API
            description: API documentation for the Library Management System.
            version: 1.0.0
        servers:
            - url: https://api-url.com # CHANGE
              description: Production Server
            - url: http://localhost:8000
              description: Local Development Server
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Document routes under /api except /api/doc
        host_patterns: # Add host-based filters if required
            - localhost
            - api-url.com # CHANGE
