security:
    password_hashers:
        App\Entity\Member:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Member
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
