services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    # Make controllers public and tag them for argument injection
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true

    App\Security\LoginSuccessHandler: ~
    App\Security\LoginFailureHandler: ~
    App\Security\ApiAuthenticationEntryPoint: ~
